class_path: torchmetrics.MetricCollection
init_args:
  metrics:
    micro-f1:
      class_path: torchmetrics.classification.MultilabelF1Score
      init_args:
        average: micro
    macro-f1:
      class_path: chebai.callbacks.epoch_metrics.MacroF1
